# Generated by Django 5.2.1 on 2025-06-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_remove_livro_preco_livro_preco_aluguel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='em_destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livro',
            name='total_alugueis',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livro',
            name='total_vendas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
