# Generated by Django 5.2.4 on 2025-07-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_pedido_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='data_devolucao_prevista',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='devolvido',
            field=models.BooleanField(default=False),
        ),
    ]
