# Generated by Django 5.2.1 on 2025-07-02 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/')),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('preco_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('disponivel_para_venda', models.BooleanField(default=True)),
                ('disponivel_para_aluguel', models.BooleanField(default=True)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('em_destaque', models.BooleanField(default=False)),
                ('total_vendas', models.PositiveIntegerField(default=0)),
                ('total_alugueis', models.PositiveIntegerField(default=0)),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='livros.genero')),
            ],
        ),
    ]
